# Generated by Django 3.2.4 on 2021-06-15 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('exam_key', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='media/exams')),
                ('questions', models.TextField(blank=True, null=True)),
                ('options', models.TextField(blank=True, max_length=1000, null=True)),
                ('security_level', models.CharField(blank=True, choices=[('Require High Security Mode', 'Require High Security Mode'), ('Allow any browser but prefer high security mode', 'Allow any browser but prefer high security mode'), ('Allow any browser', 'Allow any browser')], max_length=255, null=True)),
                ('exam_open', models.BooleanField(default=False, verbose_name='Open/Close')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_key', models.CharField(max_length=255)),
                ('started', models.BooleanField(default=False)),
                ('bio_data', models.TextField()),
                ('answer', models.TextField()),
                ('student_id', models.CharField(max_length=255)),
                ('student_submission_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('logged out', 'logged out')], max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswerPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/answers')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('owner', 'owner'), ('viewer', 'viewer')], max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Exam Access',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examgroup'),
        ),
        migrations.AddField(
            model_name='exam',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
