# Generated by Django 3.2.4 on 2021-06-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='questions',
            new_name='editor',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='pdf_file',
            new_name='uploadpdf',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_key',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_open',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='group',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='options',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='security_level',
        ),
        migrations.AddField(
            model_name='exam',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='nodigital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
