# Generated by Django 3.2.4 on 2021-06-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_exam_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
