# Generated by Django 3.2.4 on 2021-06-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_exam_uploadpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examgroup'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='uploadpdf',
            field=models.FileField(blank=True, null=True, upload_to='exams/'),
        ),
    ]
