# Generated by Django 3.2.4 on 2021-06-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20210617_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_open',
            field=models.BooleanField(default=False, verbose_name='Open/Close'),
        ),
    ]
