# Generated by Django 3.2.4 on 2021-06-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20210617_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='nodigital',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
