# Generated by Django 3.2.4 on 2021-07-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_answer_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='started_exam',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
