# Generated by Django 3.2.4 on 2021-07-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_exam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='resume_exam_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
