# Generated by Django 3.2.4 on 2021-07-12 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_exam_resume_exam_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='anonymize',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='email',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='teacher_name',
        ),
    ]
