# Generated by Django 3.2.4 on 2021-07-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_auto_20210712_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='fn',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
