# Generated by Django 3.2.4 on 2021-07-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_auto_20210712_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='anonymize',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='first_name',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='fn',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='last_name',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='student_class',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='student_id',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_name',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
