# Generated by Django 3.2.4 on 2021-07-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0027_exam_submitteddd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='fn',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='submitteddd',
        ),
    ]
