# Generated by Django 3.2.4 on 2021-07-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_auto_20210713_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
