# Generated by Django 3.2.4 on 2021-07-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_exam_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='public',
        ),
        migrations.AlterField(
            model_name='exam',
            name='anonymize',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='first_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='last_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='student_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='student_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher_name',
            field=models.BooleanField(default=False),
        ),
    ]
