# Generated by Django 3.2.4 on 2021-07-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0030_auto_20210713_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='email',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='teacher_name',
        ),
        migrations.AlterField(
            model_name='exam',
            name='first_name',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
