# Generated by Django 3.2.4 on 2021-07-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0031_auto_20210713_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='first_name',
            field=models.BooleanField(default=False),
        ),
    ]
