# Generated by Django 3.2.4 on 2021-07-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0032_alter_exam_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='last_name',
            field=models.BooleanField(default=False),
        ),
    ]
