# Generated by Django 3.2.4 on 2021-07-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0033_exam_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='student_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='student_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher_name',
            field=models.BooleanField(default=False),
        ),
    ]
