# Generated by Django 3.2.4 on 2021-07-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0034_auto_20210714_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='any_browser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='prefer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='require_high_security',
            field=models.BooleanField(default=False),
        ),
    ]
