# Generated by Django 3.2.4 on 2021-07-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0035_auto_20210722_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='prefer',
            new_name='prefer_high_security',
        ),
    ]
