# Generated by Django 3.2.5 on 2021-07-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0036_rename_prefer_exam_prefer_high_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='browser_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
