# Generated by Django 3.2.5 on 2021-08-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0037_answer_browser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
