# Generated by Django 3.2.5 on 2021-08-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0038_alter_answer_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.DateTimeField(blank=True, help_text='duration of exam in minutes', null=True),
        ),
    ]
