# Generated by Django 3.2.5 on 2021-09-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0039_alter_exam_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='teacher_name',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
    ]
