# Generated by Django 3.2.5 on 2021-09-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0040_alter_answer_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='first_name',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='last_name',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
    ]
