# Generated by Django 3.2.5 on 2021-09-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0041_auto_20210909_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='calc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='desmos_calc',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
