# Generated by Django 3.2.5 on 2021-09-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0044_answer_student_secrete_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reveal_details',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
