# Generated by Django 3.2.5 on 2021-10-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0045_answer_reveal_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='reveal_details',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
